# 🔶 GIT-005: Example Git Configuration Integration - 📝
# This file demonstrates the comprehensive Git configuration options
# available through the GIT-005 Git configuration integration feature.

# Basic backup settings
archive_dir_path: "~/Archives"
backup_dir_path: "~/Backups"
use_current_dir_name: true

# Legacy Git settings (still supported for backward compatibility)
include_git_info: true
show_git_dirty_status: true

# 🔶 GIT-005: New comprehensive Git configuration section - 📝
git:
  # Basic Git integration settings
  enabled: true                    # Enable/disable Git integration entirely
  include_info: true              # Include Git info in operations (overrides legacy include_git_info)
  show_dirty_status: true         # Show dirty status indicator (overrides legacy show_git_dirty_status)
  
  # Git command configuration
  command: "git"                  # Git command path (useful for custom Git installations)
  working_directory: "."          # Working directory for Git operations
  
  # Git behavior settings
  require_clean_repo: false       # Fail operations if repository has uncommitted changes
  auto_detect_repo: true          # Automatically detect Git repositories
  include_submodules: true        # Include submodule information in operations
  
  # Git information inclusion control
  include_branch: true            # Include branch name in archive/backup names
  include_hash: true              # Include commit hash in archive/backup names
  include_status: true            # Include working directory status in operations
  
  # Git command timeouts and limits
  command_timeout: "30s"          # Timeout for Git command execution
  max_submodule_depth: 3          # Maximum depth for submodule recursion

# File exclusion patterns
exclude_patterns:
  - ".git/"
  - "node_modules/"
  - "*.tmp"
  - "*.log"

# Archive verification settings
verification:
  verify_on_create: true
  checksum_algorithm: "sha256"

# Status codes remain unchanged
status_created_archive: 0
status_failed_to_create_archive_directory: 31

# Format strings for output
format_created_archive: "Created archive: %s (branch: %s, hash: %s)\n"
format_identical_archive: "Directory is identical to existing archive: %s\n" 